## Task 3: Statistical Validation of Key Hypotheses

In [3]:
import sys
print(sys.executable)

/home/samrawit/anaconda3/envs/myenv/bin/python

In [1]:
import sys
print(sys.executable)

import pandas as pd
import numpy as np
import scipy.stats as stats
import statsmodels.api as sm

/home/samrawit/anaconda3/envs/myenv/bin/python

In [5]:
data = pd.read_csv('/home/samrawit/End-to-End-Insurance-Risk-Analytics-Predictive-Modeling/data/processed/MLRnew.csv')

/tmp/ipykernel_19389/1807612790.py:1: DtypeWarning: Columns (32,37) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv('/home/samrawit/End-to-End-Insurance-Risk-Analytics-Predictive-Modeling/data/processed/MLRnew.csv')

In [6]:
data.head()

,UnderwrittenCoverID,PolicyID,TransactionMonth,IsVATRegistered,Citizenship,LegalType,Title,Language,Bank,AccountType,...,ExcessSelected,CoverCategory,CoverType,CoverGroup,Section,Product,StatutoryClass,StatutoryRiskType,TotalPremium,TotalClaims
0,145249,12827,2015-03-01,True,,Close Corporation,Mr,English,First National Bank,Current account,...,Mobility - Windscreen,Windscreen,Windscreen,Comprehensive - Taxi,Motor Comprehensive,Mobility Metered Taxis: Monthly,Commercial,IFRS Constant,21.929825,0.0
1,145249,12827,2015-05-01,True,,Close Corporation,Mr,English,First National Bank,Current account,...,Mobility - Windscreen,Windscreen,Windscreen,Comprehensive - Taxi,Motor Comprehensive,Mobility Metered Taxis: Monthly,Commercial,IFRS Constant,21.929825,0.0
2,145249,12827,2015-07-01,True,,Close Corporation,Mr,English,First National Bank,Current account,...,Mobility - Windscreen,Windscreen,Windscreen,Comprehensive - Taxi,Motor Comprehensive,Mobility Metered Taxis: Monthly,Commercial,IFRS Constant,0.000000,0.0
3,145255,12827,2015-05-01,True,,Close Corporation,Mr,English,First National Bank,Current account,...,Mobility - Metered Taxis - R2000,Own damage,Own Damage,Comprehensive - Taxi,Motor Comprehensive,Mobility Metered Taxis: Monthly,Commercial,IFRS Constant,512.848070,0.0
4,145255,12827,2015-07-01,True,,Close Corporation,Mr,English,First National Bank,Current account,...,Mobility - Metered Taxis - R2000,Own damage,Own Damage,Comprehensive - Taxi,Motor Comprehensive,Mobility Metered Taxis: Monthly,Commercial,IFRS Constant,0.000000,0.0

In [8]:
data.columns

Index(['UnderwrittenCoverID', 'PolicyID', 'TransactionMonth',
       'IsVATRegistered', 'Citizenship', 'LegalType', 'Title', 'Language',
       'Bank', 'AccountType', 'MaritalStatus', 'Gender', 'Country', 'Province',
       'PostalCode', 'MainCrestaZone', 'SubCrestaZone', 'ItemType', 'mmcode',
       'VehicleType', 'RegistrationYear', 'make', 'Model', 'Cylinders',
       'cubiccapacity', 'kilowatts', 'bodytype', 'NumberOfDoors',
       'VehicleIntroDate', 'CustomValueEstimate', 'AlarmImmobiliser',
       'TrackingDevice', 'CapitalOutstanding', 'NewVehicle', 'WrittenOff',
       'Rebuilt', 'Converted', 'CrossBorder', 'NumberOfVehiclesInFleet',
       'SumInsured', 'TermFrequency', 'CalculatedPremiumPerTerm',
       'ExcessSelected', 'CoverCategory', 'CoverType', 'CoverGroup', 'Section',
       'Product', 'StatutoryClass', 'StatutoryRiskType', 'TotalPremium',
       'TotalClaims'],
      dtype='object')

### Claim Frequency

In [9]:
# Create a new column for Claim Frequency
data['ClaimFrequency'] = np.where(data['TotalClaims'] > 0, 1, 0)

In [10]:
# Calculate the overall claim frequency
overall_claim_frequency = data['ClaimFrequency'].mean()
print("Overall Claim Frequency:", overall_claim_frequency)

Overall Claim Frequency: 0.002787726802773328

## Claim Severity

In [11]:
# Create a column to indicate if a claim has been made
data['HasClaim'] = data['TotalClaims'] > 0

# Calculate Claim Severity only for those who made a claim
data['ClaimSeverity'] = np.where(data['HasClaim'], data['TotalClaims'] / data['TotalPremium'], 0)

# To get the average claim severity for those who made a claim
average_claim_severity = data[data['HasClaim']]['ClaimSeverity'].mean()
print("Average Claim Severity:", average_claim_severity)

Average Claim Severity: inf

The output of Average Claim Severity: inf indicates that there is a division by zero occurring in the calculation of ClaimSeverity. This typically happens when TotalPremium is zero for some records where TotalClaims is greater than zero.

In [13]:
zero_premium_count = data[data['TotalPremium'] == 0].shape[0]
print("Number of records with zero TotalPremium:", zero_premium_count)

Number of records with zero TotalPremium: 381634

In [12]:
# Create a column to indicate if a claim has been made
data['HasClaim'] = data['TotalClaims'] > 0

# Calculate Claim Severity only for those who made a claim
data['ClaimSeverity'] = np.where(data['HasClaim'] & (data['TotalPremium'] > 0),
                                  data['TotalClaims'] / data['TotalPremium'],
                                  0)

# To get the average claim severity for those who made a claim
average_claim_severity = data[data['HasClaim'] & (data['TotalPremium'] > 0)]['ClaimSeverity'].mean()
print("Average Claim Severity:", average_claim_severity)

Average Claim Severity: 81.94613366805969

### Margin

In [16]:
data['Margin'] = data['TotalPremium'] - data['TotalClaims']
data.head()

,UnderwrittenCoverID,PolicyID,TransactionMonth,IsVATRegistered,Citizenship,LegalType,Title,Language,Bank,AccountType,...,Section,Product,StatutoryClass,StatutoryRiskType,TotalPremium,TotalClaims,ClaimFrequency,HasClaim,ClaimSeverity,Margin
0,145249,12827,2015-03-01,True,,Close Corporation,Mr,English,First National Bank,Current account,...,Motor Comprehensive,Mobility Metered Taxis: Monthly,Commercial,IFRS Constant,21.929825,0.0,0,False,0.0,21.929825
1,145249,12827,2015-05-01,True,,Close Corporation,Mr,English,First National Bank,Current account,...,Motor Comprehensive,Mobility Metered Taxis: Monthly,Commercial,IFRS Constant,21.929825,0.0,0,False,0.0,21.929825
2,145249,12827,2015-07-01,True,,Close Corporation,Mr,English,First National Bank,Current account,...,Motor Comprehensive,Mobility Metered Taxis: Monthly,Commercial,IFRS Constant,0.000000,0.0,0,False,0.0,0.000000
3,145255,12827,2015-05-01,True,,Close Corporation,Mr,English,First National Bank,Current account,...,Motor Comprehensive,Mobility Metered Taxis: Monthly,Commercial,IFRS Constant,512.848070,0.0,0,False,0.0,512.848070
4,145255,12827,2015-07-01,True,,Close Corporation,Mr,English,First National Bank,Current account,...,Motor Comprehensive,Mobility Metered Taxis: Monthly,Commercial,IFRS Constant,0.000000,0.0,0,False,0.0,0.000000

### Data Segmentation

Segmentation by Province

In [17]:
group_a = data[data['Province'] == 'Western Cape']
group_b = data[data['Province'] == 'Gauteng']

### Statistical Testing

Chi-Squared Test for Categorical Data

In [21]:
# Chi-squared test for Gender across Provinces
contingency_table = pd.crosstab(data['Province'], data['Gender'])
chi2, p_gender, dof, expected = stats.chi2_contingency(contingency_table)

print("Chi-squared Test p-value for Gender:", p_gender)

# Interpret results
if p_gender < 0.05:
    print("Reject the null hypothesis: Gender has a significant impact on Province.")
else:
    print("Fail to reject the null hypothesis: Gender does not have a significant impact on Province.")

Chi-squared Test p-value for Gender: 0.0
Reject the null hypothesis: Gender has a significant impact on Province.

T-Test for Numerical Data

In [22]:
# T-test for Margin between the two groups
t_stat_margin, p_val_margin = stats.ttest_ind(group_a['Margin'].dropna(), group_b['Margin'].dropna())
print("T-test for Margin p-value:", p_val_margin)

# Interpret results
if p_val_margin < 0.05:
    print("Reject the null hypothesis: The Province has a significant impact on Margin.")
else:
    print("Fail to reject the null hypothesis: The Province does not have a significant impact on Margin.")

T-test for Margin p-value: 0.1567334972436032
Fail to reject the null hypothesis: The Province does not have a significant impact on Margin.